# Generated by Django 5.0.1 on 2024-02-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_likedpost_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
