# Generated by Django 5.0.1 on 2024-02-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxTitle', models.CharField(max_length=50)),
                ('boxImage', models.ImageField(blank=True, null=True, upload_to='adminImages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming_events_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxTitle', models.CharField(max_length=50)),
                ('boxImage', models.ImageField(blank=True, null=True, upload_to='adminImages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxTitle', models.CharField(max_length=50)),
                ('boxImage', models.ImageField(blank=True, null=True, upload_to='adminImages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
